{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dspace.fullname" . }}-db
  labels:
    {{- include "dspace.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: db-port
      protocol: TCP
      name: db-port-svc
  selector:
    {{- include "dspace.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
