{{- if .Values.services.memcached.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
  name: {{ .Values.services.memcached.name }}
spec:
  ports:
    - name: memcached
      port: {{ .Values.services.memcached.servicePort }}
      targetPort: memcached
  selector:
    {{- include "memcached.selectorLabels" . | nindent 6 }}
status:
  loadBalancer: {}
{{- end }}
