apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dspace.backendFullname" . }}-configs
  labels:
    {{- include "dspace.labels" . | nindent 4 }}
data: 
  {{- with .Values.config }}
  dspace__P__dir: {{ .dir }}
  dspace__P__server__P__url: {{ printf "http://%s%s" .server.host .server.path }}
  dspace__P__ui__P__url: {{ printf "http://%s%s" .ui.host .ui.path }}
  dspace__P__name: {{ .name }}
  {{- if .proxiesTrustedIPRanges -}}
  proxies__P__trusted__P__ipranges: {{ .proxiesTrustedIPRanges }}
  {{- end }}
  CATALINA_OPTS: {{ .jvm.CATALINA_OPTS }}
  {{- end }}
