{{- $dbHost := printf "%s.%s.svc.cluster.local" (include "dspace.dbFullname" .) .Release.Namespace -}}
{{- $solrHost := printf "http://%s.%s.svc.cluster.local:8983/solr" (include "dspace.solrFullname" .) .Release.Namespace -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "dspace.backendFullname" . }}-credentials
  labels:
    {{- include "dspace.labels" . | nindent 4 }}
stringData:
  {{- with .Values.config }}
  {{- $dbHost = ternary .db.host $dbHost .db.external }}
  {{- $dbPort := ternary .db.port 5432 .db.external }}
  db__P__url: {{ printf "jdbc:postgresql://%s:%s/%s" $dbHost ($dbPort | toString ) .db.dbName }}
  db__P__username: {{ .db.username }}
  db__P__password: {{ .db.password }}
  solr__P__server: {{ default .solr.server $solrHost }}
  {{- end }}
type: Opaque