apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "geonode.fullname" . }}-statics
  labels:
    {{- include "geonode.labels" . | nindent 4 }}
{{- with .Values.volumes.statics }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .storage }}
{{- end }}
