apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mapserver.fullname" . }}
  labels:
    {{- include "mapserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mapserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mapserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mapserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- if .Values.pvc.enabled }}
        - name: mapserver-data
          persistentVolumeClaim:
            claimName: {{ include "mapserver.fullname" . }}-pvc
        {{- end }}
        {{- if .Values.msencrypt.enabled }}
        - name: mapserver-encrypt-key
          secret:
            secretName: {{ include "mapserver.fullname" . }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.msencrypt.enabled }}
            - name: MS_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mapserver.fullname" . }}
                  key: MS_ENCRYPTION_KEY
            {{- end }}
          volumeMounts:
            {{- if .Values.pvc.enabled }}
            - name: mapserver-data
              mountPath: {{ .Values.pvc.storage.mountPath }}
            {{- end }}
            {{- if .Values.msencrypt.enabled }}
            - name: mapserver-encrypt-key
              mountPath: {{ .Values.msencrypt.mountPath }}          
              readOnly: true
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP          
          livenessProbe:
            {{- if contains "fcgi" .Values.image.tag }}
            exec:
              command:
                - /usr/bin/pidof
                - "-xsq"
                - mapserv
            {{- else }}
            httpGet:
              path: /
              port: http
            {{- end }}
          readinessProbe:
            {{- if contains "fcgi" .Values.image.tag }}
            tcpSocket:
              port: http
            {{- else }}
            httpGet:
              path: /
              port: http
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
