kind: Secret
apiVersion: v1
metadata:
  name: {{ include "mapserver.fullname" . }}
  labels:
    {{- include "mapserver.labels" . | nindent 4 }}  
stringData:
  MS_ENCRYPTION_KEY: {{ .Values.msencrypt.mountPath }}/mskey.txt
  mskey.txt: {{ .Values.msencrypt.key }}  
type: Opaque
