serviceAccount:
  name: geonode 
services:
  nginx:
    config:
      resolver: 10.217.4.10
    image:
      repository: ndscprm/nginx
      tag: dev
    # securityContext:
    #   runAsNonRoot: true
  django:
    image: 
      repository: ndscprm/geonode
      tag: dev
    # securityContext:
    #   runAsNonRoot: true
  celery:
    image:
      repository: ndscprm/geonode  
      tag: dev
    # securityContext:
    #   runAsNonRoot: true
  geoserver:
    image:
      app:
        repository: ndscprm/geoserver
        tag: dev
      data:
        repository: ndscprm/geoserver_data
        tag: dev
    # securityContext:
    #   runAsNonRoot: true
configs:
  admin:
    password: 123456
  oAuth2:
    apiKey: abcderfhijklmnopqrstuvwxyz
    clientId: abc
    secret: 1234567890
  django:
    secretKey: M<]M/$CpU9YXR5nNmPqCj73UXi,n>) X,[zRj6T=2Sj==Z}vWd
  # mail:
  #   enabled: true
  memcached:
    enabled: true

