{{- if .Values.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mapproxy.fullname" . }}-pvc
  labels:
    {{- include "mapproxy.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  {{- with .Values.pvc.storage }}
  {{- if .className }}
  storageClassName: {{ .className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
  {{- end }}
{{- end }}