{{- if .Values.configs.mail.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geonode.mail-secret" . }}
type: Opaque
stringData: 
  {{ with .Values.configs.mail }}
  DJANGO_EMAIL_HOST: {{ .host }}
  DJANGO_EMAIL_PORT: {{ .port | toString | quote }}
  DJANGO_EMAIL_HOST_USER: {{ .user | toString | quote }}
  DJANGO_EMAIL_HOST_PASSWORD: {{ .password | toString | quote }} 
  DJANGO_EMAIL_USE_TLS: {{ .useTLS | toString | title | quote }}
  DJANGO_EMAIL_USE_SSL: {{ .useSSL | toString | title | quote }}
  {{ end }}
{{- end }}
