{{- if .Values.services.memcached.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geonode.memcached-secret" . }}
type: Opaque
stringData: 
  MEMCACHED_BACKEND: django.core.cache.backends.memcached.MemcachedCache
  MEMCACHED_LOCATION: {{ include "memcached.internalPath" . }}
  MEMCACHED_LOCK_EXPIRE: "3600"
  MEMCACHED_LOCK_TIMEOUT: "10"
  #
  # Options for memcached binary, e.g. -vvv to log all requests and cache hits
  #
  MEMCACHED_OPTIONS: ""
{{- end }}
