{{- $memcachedSecret := include "geonode.memcached-secret" . -}}
{{- $memcachedHost := include "geonode.memcached.hostname" .}}
{{- if or .Values.memcached.enabled ( not (empty .Values.configs.memcached.location) ) }}
{{- with .Values.configs.memcached }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $memcachedSecret }}
type: Opaque
stringData:
  {{- if .backend }}
  MEMCACHED_BACKEND: {{ .backend | quote }}
  {{- end }}
  MEMCACHED_LOCATION: {{ $memcachedHost }}
  {{- if .lockExpire }}
  MEMCACHED_LOCK_EXPIRE: {{ .lockExpire | toString | quote }}
  {{- end }}
  {{- if .lockTimeout }}
  MEMCACHED_LOCK_TIMEOUT: {{ .lockTimeout | toString | quote }}
  {{- end }}
  {{- if .options }}
  # Options for memcached binary, e.g. -vvv to log all requests and cache hits
  MEMCACHED_OPTIONS: {{ .options | quote }}
  {{- end }}
{{- end }}
{{- end }}
