{{- $memcachedSecret := include "geonode.memcached-secret" . -}}
{{- $internalPath := include "memcached.internalPath" . -}}
{{- with .Values.configs.memcached }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $memcachedSecret }}
type: Opaque
stringData:
  {{- if .backend }}
  MEMCACHED_BACKEND: {{ .backend | quote }}
  {{- end }}
  {{- if not .location }}
  MEMCACHED_LOCATION: {{ $internalPath | quote }}
  {{- end }}
  {{- if .lockExpire }}
  MEMCACHED_LOCK_EXPIRE: {{ .lockExpire | toString | quote }}
  {{- end }}
  {{- if .lockTimeout }}
  MEMCACHED_LOCK_TIMEOUT: {{ .lockTimeout | toString | quote }}
  {{- end }}
  {{- if .options }}
  # Options for memcached binary, e.g. -vvv to log all requests and cache hits
  MEMCACHED_OPTIONS: {{ .options | quote }}
  {{- end }}
{{- end }}
{{- end }}
