{{- if .Values.configs.recaptcha.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geonode.recaptcha-secret" . }}
type: Opaque
stringData: 
  {{ with .Values.configs.recaptcha }}
  RECAPTCHA_ENABLED: {{ .enabled | toString | title | quote }}
  RECAPTCHA_PUBLIC_KEY: {{ .publicKey }}
  RECAPTCHA_PRIVATE_KEY: {{ .privateKey }}
  ACCOUNT_SIGNUP_FORM_CLASS: {{ .signupFormClass }}
  {{ end }}
{{- end }}
