apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
  name: {{ .Values.services.geoserver.name }}
spec:
  ports:
    - name: http-alt
      port: {{ .Values.services.geoserver.servicePort }}
      targetPort: http-alt
  selector:
    {{- include "geoserver.selectorLabels" . | nindent 6 }}
status:
  loadBalancer: {}
