apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../geonode-stack.yml --controller deployment --provider kubernetes -c -o geonode
    kompose.controller.type: deployment
    kompose.serviceaccount-name: geonode-sa
    kompose.version: 1.28.0 (c4137012e)
    kompose.volume.size: 1Gi
  creationTimestamp: null
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  name: {{ .Values.services.nginx.name }}
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "https"
      port: 443
      targetPort: 443
  selector:
    {{- include "nginx.selectorLabels" . | nindent 6 }}
status:
  loadBalancer: {}
