apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sqlserver.fullname" . }}
data:    
  ACCEPT_EULA: {{ .Values.env.ACCEPT_EULA | quote }}
  MSSQL_ENABLE_HADR: {{ .Values.env.MSSQL_ENABLE_HADR | quote }}
  MSSQL_AGENT_ENABLED: {{ .Values.env.MSSQL_AGENT_ENABLED | quote }}
