apiVersion: v1
kind: Service
metadata:
  name: {{ include "sqlserver.fullname" . }}
  labels:
    {{- include "sqlserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcpsql
      protocol: TCP
      name: tcpsql
  selector:
    {{- include "sqlserver.selectorLabels" . | nindent 4 }}
