{{- if .Values.overrides.conf_d.default -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-conf.d
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  default.conf: {{ .Values.overrides.conf_d.default | toYaml | indent 2 }} 
{{- end }}