{{- $nginx := include "nginx.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $nginx }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nginx.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nginx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{ with .Values.overrides }}
        {{- if ( and .html .html.enabled ) }}
        - name: {{ $nginx }}-html
          {{ .html.type | default "emptyDir" }}:
            name: {{ .html.name }}
        {{- end }}
        {{- if ( and .default .default.enabled ) }}
        - name: {{ $nginx }}-default
          {{ .default.type | default "emptyDir" }}:
            name: {{ .default.name }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            {{ with .Values.overrides }}
            {{- if ( and .html .html.enabled ) }}
            - name: {{ $nginx }}-html
              readOnly: true
              mountPath: /usr/share/nginx/html
            {{- end }}
            {{- if ( and .default .default.enabled ) }}
            - name: {{ $nginx }}-default
              readOnly: true
              mountPath: /etc/nginx/conf.d
            {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
