apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq.fullname" . }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 61616
      targetPort: jms
      protocol: TCP
      name: jms
  selector:
    {{- include "activemq.selectorLabels" . | nindent 4 }}
