apiVersion: v2
name: mapserver
version: 0.1.0
description: |-
  MapServer is an Open Source platform for publishing spatial data and interactive mapping applications to the web. 
  Originally developed in the mid-1990’s at the University of Minnesota, MapServer is released under an MIT-style 
  license, and runs on all major platforms (Windows, Linux, Mac OS X). MapServer is not a full-featured GIS system, 
  nor does it aspire to be.
type: application
keywords:
  - GIS
  - FOSS4G
  - webmap
  - WMS
  - WFS
  - WCS
home: https://mapserver.org/
sources:
  - https://github.com/MapServer/MapServer
  - https://github.com/nds-cprm/mapserver-oci
maintainers:
  - name: Carlos Eduardo Mota
    email: carlos.mota@sgb.gov.br
icon: "https://mapserver.org/_static/banner.png"
appVersion: "7.6.5"
