{{- if .Values.config.ui.configFile -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dspace.frontendFullname" . }}-ui-config
  labels:
    {{- include "dspace.labels" . | nindent 4 }}
data: 
  config.yml: |
    {{- .Values.config.ui.configFile }}
{{- end -}}
