apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dspace.frontendFullname" . }}
  labels:
    {{- include "dspace.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dspace.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dspace.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dspace.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default ( printf "%s-dist" .Chart.AppVersion ) }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: frontend-port
              containerPort: 4000
              protocol: TCP
          env:
            - name: DSPACE_UI_SSL
              value: "false"
            - name: DSPACE_UI_HOST
              value: "0.0.0.0"
            - name: DSPACE_UI_PORT
              value: "4000"
            - name: DSPACE_UI_NAMESPACE
              value: "/"
            - name: DSPACE_REST_SSL
              value: "false"
            - name: DSPACE_REST_HOST
              value: {{ .Values.ingress.backend.host }}
            - name: DSPACE_REST_PORT
              value: "80"
            - name: DSPACE_REST_NAMESPACE
              value:  {{ .Values.ingress.backend.path }}
          livenessProbe:
            tcpSocket:
              port: frontend-port
          readinessProbe:
            httpGet:
              path: /home
              port: frontend-port          
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', 'wget --spider http://{{ include "dspace.fullname" . }}-backend:8080/server']
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
