apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../geonode-stack.yml --controller deployment --provider kubernetes -c -o geonode
    kompose.controller.type: statefulset
    kompose.serviceaccount-name: geonode-sa
    kompose.version: 1.28.0 (c4137012e)
    kompose.volume.size: 1Gi
  creationTimestamp: null
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  name: {{ .Values.services.rabbitmq.name }}
spec:
  ports:
    - name: amqp
      port: {{ .Values.services.rabbitmq.servicePort}}
      targetPort: amqp
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 6 }}
status:
  loadBalancer: {}
