apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  name: {{ .Values.services.rabbitmq.name }}
spec:
  ports:
    - name: amqp
      port: {{ .Values.services.rabbitmq.servicePort}}
      targetPort: amqp
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 6 }}
status:
  loadBalancer: {}
