{{- if .Values.route.enabled }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.services.nginx.name }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ .Values.services.nginx.name }}
  tls: null
  # tls:
  #   termination: edge
  #   insecureEdgeTerminationPolicy: Redirect
  #   destinationCACertificate: ''
  host: {{ include "geonode.hostname" . }}
  path: /
  port:
    targetPort: http
{{- end }}
