apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geonode.name" . }}-postgres
type: Opaque
{{- $dbhost := (include "db.hostname" .) -}}
{{- $dbIsExternal := .Values.services.db.external -}}
{{- with .Values.secrets.postgres }}
{{- $databaseUrl :=  printf "postgis://%s:%s@%s:%s/%s" .db.user .db.password $dbhost (.port | toString) .db.name -}}
{{- $geodatabaseUrl :=  printf "postgis://%s:%s@%s:%s/%s" .geoDb.user .geoDb.password $dbhost (.port | toString) .geoDb.name }}
stringData:  
  # Database runs on same server
  DATABASE_HOST: {{ $dbhost }}
  DATABASE_PORT: {{ .port | quote }}
  # Only for geonode/postgis official images
  {{- if not $dbIsExternal }}
  POSTGRES_PASSWORD: {{ .password }}
  POSTGRES_USER: {{ .user }}
  {{- end }}
  # GeoNode database
  GEONODE_DATABASE: {{ .db.name }}
  GEONODE_DATABASE_USER: {{ .db.user }}
  GEONODE_DATABASE_PASSWORD: {{ .db.password }}
  GEONODE_DATABASE_SCHEMA: {{ .db.schema }}
  # GeoNode geodatabase
  GEONODE_GEODATABASE: {{ .geoDb.name }}
  GEONODE_GEODATABASE_USER: {{ .geoDb.user }}
  GEONODE_GEODATABASE_PASSWORD: {{ .geoDb.password }}
  GEONODE_GEODATABASE_SCHEMA: {{ .geoDb.schema }}
  # Django Settings
  DATABASE_URL: {{ $databaseUrl }}
  GEODATABASE_URL: {{ $geodatabaseUrl }}  
  DEFAULT_BACKEND_DATASTORE: datastore
  GEONODE_DB_CONN_MAX_AGE: {{ .maxAge | quote }}
  GEONODE_DB_CONN_TOUT: {{ .timeOut | quote }}
{{ end }}
