{{- if .Values.configs.recaptcha.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geonode.name" . }}-recaptcha
type: Opaque
stringData: 
  {{ with .Values.configs.recaptcha }}
  RECAPTCHA_ENABLED: {{ .enabled | quote | title }}
  RECAPTCHA_PUBLIC_KEY: {{ .publicKey }}
  RECAPTCHA_PRIVATE_KEY: {{ .privateKey }}
  ACCOUNT_SIGNUP_FORM_CLASS: {{ .signupFormClass }}
  {{ end }}
{{- end }}
