apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: geonode-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              org.{{ .Chart.Name }}/network: {{ .Release.Name }}-{{ .Release.Namespace }}
  podSelector:
    matchLabels:
      org.{{ .Chart.Name }}/network: {{ .Release.Name }}-{{ .Release.Namespace }}
