{{- $fullName := include "geonode.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.celery.name }}
  labels:
    {{- include "celery.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "celery.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.services.celery.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        org.{{ .Chart.Name }}/network: {{ .Release.Name }}-{{ .Release.Namespace }}
        {{- include "celery.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - celery-cmd
          command:
            - /usr/src/{{ .Values.configs.projectName }}/entrypoint.sh
          envFrom:
            - configMapRef:
                name: {{ include "geonode.configmap" . }}
            - secretRef:
                name: {{ include "geonode.name" . }}-postgres
            {{- if .Values.configs.ldap.enabled }}
            - secretRef:
                name: {{ include "geonode.name" . }}-ldap
            {{- end }}
            {{- if .Values.services.memcached.enabled }}
            - secretRef:
                name: {{ include "geonode.name" . }}-memcached
            {{- end }}
          image: {{ .Values.services.celery.image.repository }}:{{ .Values.services.celery.image.tag | default "latest-ubuntu-22.04" }}
          imagePullPolicy: {{ .Values.services.celery.image.pullPolicy }}
          name: {{ .Values.services.celery.name }}
          securityContext:
            {{- toYaml .Values.services.celery.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.services.celery.resources | nindent 12 }}
          {{- with .Values.volumes }}
          volumeMounts:
            - mountPath: {{ .statics.mountPath }}
              name: statics
            - mountPath: {{ .geoserverData.mountPath }}
              name: geoserver-data-dir
            - mountPath: {{ .backupRestore.mountPath }}
              name: backup-restore
            - mountPath: {{ .data.mountPath }}
              name: data
            - mountPath: {{ .tmp.mountPath }}
              name: tmp
            {{- end }}
      initContainers:
        - name: wait-for-django
          image: {{ .Values.services.db.image.repository }}:{{ .Values.services.db.image.tag | default "latest" }}
          command: ['sh', '-c', "until wget --spider http://{{ .Values.services.django.name }}.{{ .Release.Namespace }}.svc.cluster.local:8000; do echo waiting for django; sleep 2; done"]
      serviceAccountName: {{ include "geonode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.services.celery.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      {{- with .Values.services.celery.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.celery.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.celery.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        - name: statics
          persistentVolumeClaim:
            claimName: {{ $fullName }}-statics
        - name: geoserver-data-dir
          persistentVolumeClaim:
            claimName: {{ $fullName }}-geoserver-data
        - name: backup-restore
          persistentVolumeClaim:
            claimName: {{ $fullName }}-backup-restore
        - name: data
          persistentVolumeClaim:
            claimName: {{ $fullName }}-data
        - name: tmp
          persistentVolumeClaim:
            claimName: {{ $fullName }}-tmp
      {{- end }}
status: {}
