apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geonetwork.fullname" . }}
  labels:
    {{- include "geonetwork.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "geonetwork.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "geonetwork.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "geonetwork.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- if .Values.pvc.data.enabled }}
        - name: geonetwork-data
          persistentVolumeClaim:
            claimName: {{ include "geonetwork.fullname" . }}-data-pvc
        {{- end }}
        {{- if .Values.pvc.index.enabled }}
        - name: geonetwork-index
          persistentVolumeClaim:
            claimName: {{ include "geonetwork.fullname" . }}-index-pvc
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-{{ .Values.service.port }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- if .Values.pvc.data.enabled }}
            - name: GEONETWORK_DATA_DIR
              value: {{ .Values.pvc.data.storage.mountPath }}
            {{- end }}
            {{- if .Values.pvc.index.enabled }}
            - name: GEONETWORK_LUCENE_DIR
              value: {{ .Values.pvc.index.storage.mountPath }}
            {{- end }}
            - name: GEONETWORK_DB_TYPE
              value: {{ if .Values.database.enabled }}{{ .Values.database.type }}{{ else }}h2{{ end }}
            {{- if .Values.database.enabled }}
            - name: GEONETWORK_DB_HOST
              valueFrom:
                secretKeyRef:
                  key:  GEONETWORK_DB_HOST
                  name: {{ include "geonetwork.fullname" . }}-db-credentials
            - name: GEONETWORK_DB_PORT
              valueFrom:
                secretKeyRef:
                  key:  GEONETWORK_DB_PORT
                  name: {{ include "geonetwork.fullname" . }}-db-credentials
            - name: GEONETWORK_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key:  GEONETWORK_DB_DATABASE
                  name: {{ include "geonetwork.fullname" . }}-db-credentials
            - name: GEONETWORK_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key:  GEONETWORK_DB_USERNAME
                  name: {{ include "geonetwork.fullname" . }}-db-credentials
            - name: GEONETWORK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key:  GEONETWORK_DB_PASSWORD
                  name: {{ include "geonetwork.fullname" . }}-db-credentials
            {{- end }}
          volumeMounts:
            {{- if .Values.pvc.data.enabled }}
            - mountPath: {{ .Values.pvc.data.storage.mountPath }}
              name: geonetwork-data
            {{- end }}
            {{- if .Values.pvc.index.enabled }}
            - mountPath: {{ .Values.pvc.index.storage.mountPath }}
              name: geonetwork-index
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: tcp-{{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /geonetwork
              port: tcp-{{ .Values.service.port }}
            initialDelaySeconds: 40
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
