apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geonetwork.fullname" . }}
  labels:
    {{- include "geonetwork.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "geonetwork.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "geonetwork.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "geonetwork.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- if .Values.pvc.data.enabled }}
        - name: geonetwork-data
          persistentVolumeClaim:
            claimName: {{ include "geonetwork.fullname" . }}-data
        {{- end }}
        {{- if .Values.pvc.index.enabled }}
        - name: geonetwork-index
          persistentVolumeClaim:
            claimName: {{ include "geonetwork.fullname" . }}-index
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-{{ .Values.service.port }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            {{- if .Values.database.enabled }}
            - secretRef:
                name: {{ include "geonetwork.fullname" . }}-db
            {{- end }}
            - configMapRef:
                name: {{ include "geonetwork.fullname" . }}-config                       
          volumeMounts:
            {{- if .Values.pvc.data.enabled }}
            - mountPath: {{ .Values.pvc.data.storage.mountPath }}
              name: geonetwork-data
            {{- end }}
            {{- if .Values.pvc.index.enabled }}
            - mountPath: {{ .Values.pvc.index.storage.mountPath }}
              name: geonetwork-index
            {{- end }}
          livenessProbe:
            httpGet:
              path: /geonetwork
              port: tcp-{{ .Values.service.port }}
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
