{{- $pvcName := printf "%s-data" (include "geonetwork.fullname" .) -}}
{{- $pvcLabels := include "geonetwork.labels" . -}}

{{- with .Values.pvc.data }}
{{- if .enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  labels:
    {{- $pvcLabels | nindent 4 }}
  {{- if .keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  volumeMode: Filesystem
  {{- if .volumeName }}
  volumeName: {{ .volumeName | quote }}
  {{- end }}
  accessModes:
    {{- range .storage.accessModes }}
    - {{ . }}
    {{- end }}
  storageClassName: {{ .storage.className | quote }}
  resources:
    requests:
      storage: {{ .storage.size }}
  {{- end }}
{{- end }}
