{{- if .Values.pvc.data.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "geonetwork.fullname" . }}-data
  labels:
    {{- include "geonetwork.labels" . | nindent 4 }}
  {{- if .Values.pvc.data.keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  volumeMode: Filesystem
  {{- if .volumeName }}
  volumeName: {{ .volumeName | quote }}
  {{- end }}
  {{- with .Values.pvc.data.storage }}
  accessModes:
    {{- range .accessModes }}
    - {{ . }}
    {{- end }}
  storageClassName: {{ .className | quote }}
  resources:
    requests:
      storage: {{ .size }}
  {{- end }}
{{- end }}
