apiVersion: v1
kind: Service
metadata:
  name: {{ include "geonetwork.fullname" . }}
  labels:
    {{- include "geonetwork.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: tcp-{{ .Values.service.port }}
  selector:
    {{- include "geonetwork.selectorLabels" . | nindent 4 }}
