{{- if not .Values.services.db.external }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "db.labels" . | nindent 4 }}
  name: {{ .Values.services.db.name }}
spec:
  ports:
    - name: "postgresql-svc"
      port: {{ .Values.configs.postgres.port }}
      targetPort: postgresql
  selector:
    {{- include "db.selectorLabels" . | nindent 6 }}
status:
  loadBalancer: {}
{{- end }}
