{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.overrides.default.name }}
  labels:
    {{- include "nginx.labels" .Subcharts.nginx | nindent 4 }}
data:
  default.conf: |-
{{ ( tpl ( .Files.Get "files/default.conf" ) . ) | indent 4 }}
{{- end -}}
