{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.overrides.html.name }}
  labels:
    {{- include "nginx.labels" .Subcharts.nginx | nindent 4 }}
data:
  index.html: |-
{{ ( tpl ( .Files.Get "files/index.html" ) . ) | indent 4 }}
{{- end -}}
