{{- $pvcEnabled := or .Values.master.pvc.enabled .Values.cluster.enabled -}}
{{- if $pvcEnabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "geoserver.master.fullname" . }}
  labels:
    {{- include "geoserver.master.labels" . | nindent 4 }}
{{- with .Values.master.pvc -}}
  {{- if .keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  volumeMode: Filesystem
  {{- if .volumeName }}
  volumeName: {{ .volumeName | quote }}
  {{- else }}
  {{-  if .storage.className }}
  storageClassName: {{ .storage.className | quote }}
  {{- end }}
  {{- end }}
  accessModes:
    {{- range .storage.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .storage.size }}
{{- end -}}
{{- end }}